# 单注册服务器
server:
   port: 8888
   
eureka:
   instance:
      hostname: localhost
   client:
      # 是否开启注册服务，因为这里如果为true表示自己注册自己，而自己就是一个服务注册方，没必要自己注册自己
      registerWithEureka: false
      # 是否拉取服务列表，这里我只提供服务给别的服务。
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
         
spring:
   application:
      name: eureka-server